name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.6

      # 3️⃣ Format Terraform (auto-fix, so CI doesn’t fail)
      - name: Terraform Format
        run: terraform fmt -recursive
        working-directory: terraform/environments/dev

      # 4️⃣ Initialize Terraform without backend
      - name: Terraform Init
        run: terraform init -backend=false -upgrade
        working-directory: terraform/environments/dev

      # 5️⃣ Get all modules
      - name: Terraform Get Modules
        run: terraform get -update
        working-directory: terraform/environments/dev

      # 6️⃣ Validate configuration
      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/environments/dev